spring:
  application:
    name: events
  jpa:
    generate-ddl: "false"
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    sql:
      init:
        mode: always

events:
  notification-enabled: true
  notification-response-enabled: false

logging:
  level:
    gae.piaz: TRACE

